# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate
    language: "fr"

binary_sensor:
  - platform: ping
    host: 192.168.1.26
    name: prout
    count: 8
    scan_interval: 30

notify:
  - platform: discord
    name: discord
    token: !secret discord_token

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
