# Load frontend themes from the themes folder
frontend:
  themes: !include_dir_merge_named themes

tts:
  - platform: google_translate
    language: "fr"

notify:
  - platform: discord
    name: discord
    token: !secret discord_token

automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
